FROM buzzingpixel/php7.2:1.0.6
COPY . /app
COPY ./serverConfig/php-schedule-runner/php-custom-config.ini /usr/local/etc/php/conf.d/php-custom-config.ini
COPY ./serverConfig/php-schedule-runner/php-config-prod.ini /usr/local/etc/php/conf.d/php-env-config.ini
COPY ./serverConfig/php-schedule-runner/fpm-www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./serverConfig/php-schedule-runner/mission-control-schedule /etc/cron.d/mission-control-schedule
RUN chmod 0644 /etc/cron.d/mission-control-schedule
RUN chmod +x /etc/cron.d/mission-control-schedule
RUN crontab /etc/cron.d/mission-control-schedule
RUN touch /var/log/cron.log
