<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\ScheduleTracking;

use Atlas\Table\Table;

/**
 * @method ScheduleTrackingRow|null fetchRow($primaryVal)
 * @method ScheduleTrackingRow[] fetchRows(array $primaryVals)
 * @method ScheduleTrackingTableSelect select(array $whereEquals = [])
 * @method ScheduleTrackingRow newRow(array $cols = [])
 * @method ScheduleTrackingRow newSelectedRow(array $cols)
 */
class ScheduleTrackingTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'schedule_tracking';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'guid' => [
            'name' => 'guid',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'is_running' => [
            'name' => 'is_running',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => '0',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'last_run_start_at' => [
            'name' => 'last_run_start_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'last_run_start_at_time_zone' => [
            'name' => 'last_run_start_at_time_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'last_run_end_at' => [
            'name' => 'last_run_end_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'last_run_end_at_time_zone' => [
            'name' => 'last_run_end_at_time_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'guid',
        'is_running',
        'last_run_start_at',
        'last_run_start_at_time_zone',
        'last_run_end_at',
        'last_run_end_at_time_zone',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'guid' => null,
        'is_running' => '0',
        'last_run_start_at' => 'NULL',
        'last_run_start_at_time_zone' => 'NULL',
        'last_run_end_at' => 'NULL',
        'last_run_end_at_time_zone' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
