<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineJob;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $pipeline_guid binary(16)
 * @property mixed $has_started tinyint(3,0) NOT NULL
 * @property mixed $is_finished tinyint(3,0) NOT NULL
 * @property mixed $has_failed tinyint(3,0) NOT NULL
 * @property mixed $percent_complete float(12) NOT NULL
 * @property mixed $job_added_at datetime
 * @property mixed $job_added_at_time_zone varchar(255)
 * @property mixed $job_finished_at datetime
 * @property mixed $job_finished_at_zone varchar(255)
 */
class PipelineJobRow extends Row
{
    protected $cols = [
        'guid' => null,
        'pipeline_guid' => 'NULL',
        'has_started' => 0,
        'is_finished' => 0,
        'has_failed' => 0,
        'percent_complete' => 0.0,
        'job_added_at' => 'NULL',
        'job_added_at_time_zone' => 'NULL',
        'job_finished_at' => 'NULL',
        'job_finished_at_zone' => 'NULL',
    ];
}
