<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineJob;

use Atlas\Table\Table;

/**
 * @method PipelineJobRow|null fetchRow($primaryVal)
 * @method PipelineJobRow[] fetchRows(array $primaryVals)
 * @method PipelineJobTableSelect select(array $whereEquals = [])
 * @method PipelineJobRow newRow(array $cols = [])
 * @method PipelineJobRow newSelectedRow(array $cols)
 */
class PipelineJobTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'pipeline_jobs';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'pipeline_guid' => [
            'name' => 'pipeline_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'has_started' => [
            'name' => 'has_started',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'is_finished' => [
            'name' => 'is_finished',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'has_failed' => [
            'name' => 'has_failed',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'percent_complete' => [
            'name' => 'percent_complete',
            'type' => 'float',
            'size' => 12,
            'scale' => null,
            'notnull' => true,
            'default' => 0.0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'job_added_at' => [
            'name' => 'job_added_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'job_added_at_time_zone' => [
            'name' => 'job_added_at_time_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'job_finished_at' => [
            'name' => 'job_finished_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'job_finished_at_zone' => [
            'name' => 'job_finished_at_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'pipeline_guid',
        'has_started',
        'is_finished',
        'has_failed',
        'percent_complete',
        'job_added_at',
        'job_added_at_time_zone',
        'job_finished_at',
        'job_finished_at_zone',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'pipeline_guid' => 'NULL',
        'has_started' => 0,
        'is_finished' => 0,
        'has_failed' => 0,
        'percent_complete' => 0.0,
        'job_added_at' => 'NULL',
        'job_added_at_time_zone' => 'NULL',
        'job_finished_at' => 'NULL',
        'job_finished_at_zone' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
