<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineJob;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $pipeline_guid binary(16)
 * @property mixed $has_started tinyint(3,0) NOT NULL
 * @property mixed $is_finished tinyint(3,0) NOT NULL
 * @property mixed $has_failed tinyint(3,0) NOT NULL
 * @property mixed $percent_complete float(12) NOT NULL
 * @property mixed $job_added_at datetime
 * @property mixed $job_added_at_time_zone varchar(255)
 * @property mixed $job_finished_at datetime
 * @property mixed $job_finished_at_zone varchar(255)
 * @property null|\src\app\data\PipelineJobItem\PipelineJobItemRecordSet $pipeline_job_items
 */
trait PipelineJobFields
{
}
