<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineItem;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $pipeline_guid binary(16)
 * @property mixed $order int(10,0) NOT NULL
 * @property mixed $type varchar(255)
 * @property mixed $description varchar(255)
 * @property mixed $script text(65535) NOT NULL
 * @property mixed $run_after_fail tinyint(3,0) NOT NULL
 */
class PipelineItemRow extends Row
{
    protected $cols = [
        'guid' => null,
        'pipeline_guid' => 'NULL',
        'order' => null,
        'type' => '\'code\'',
        'description' => 'NULL',
        'script' => null,
        'run_after_fail' => 0,
    ];
}
