<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\MonitoredUrlIncident;

use Atlas\Table\Table;

/**
 * @method MonitoredUrlIncidentRow|null fetchRow($primaryVal)
 * @method MonitoredUrlIncidentRow[] fetchRows(array $primaryVals)
 * @method MonitoredUrlIncidentTableSelect select(array $whereEquals = [])
 * @method MonitoredUrlIncidentRow newRow(array $cols = [])
 * @method MonitoredUrlIncidentRow newSelectedRow(array $cols)
 */
class MonitoredUrlIncidentTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'monitored_url_incidents';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'guid' => [
            'name' => 'guid',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'monitored_url_guid' => [
            'name' => 'monitored_url_guid',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'event_type' => [
            'name' => 'event_type',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'status_code' => [
            'name' => 'status_code',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'message' => [
            'name' => 'message',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'event_at' => [
            'name' => 'event_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'event_at_time_zone' => [
            'name' => 'event_at_time_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'guid',
        'monitored_url_guid',
        'event_type',
        'status_code',
        'message',
        'event_at',
        'event_at_time_zone',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'guid' => null,
        'monitored_url_guid' => null,
        'event_type' => null,
        'status_code' => null,
        'message' => null,
        'event_at' => null,
        'event_at_time_zone' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
