<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\MonitoredUrlIncident;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $guid varchar(255) NOT NULL
 * @property mixed $monitored_url_guid varchar(255) NOT NULL
 * @property mixed $event_type varchar(255) NOT NULL
 * @property mixed $status_code varchar(255) NOT NULL
 * @property mixed $message text(65535) NOT NULL
 * @property mixed $event_at datetime NOT NULL
 * @property mixed $event_at_time_zone varchar(255) NOT NULL
 */
trait MonitoredUrlIncidentFields
{
}
