<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\MonitoredUrlIncident;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $monitored_url_guid binary(16) NOT NULL
 * @property mixed $event_type varchar(255) NOT NULL
 * @property mixed $status_code varchar(255) NOT NULL
 * @property mixed $message text(65535) NOT NULL
 * @property mixed $event_at datetime NOT NULL
 * @property mixed $event_at_time_zone varchar(255) NOT NULL
 */
class MonitoredUrlIncidentRow extends Row
{
    protected $cols = [
        'guid' => null,
        'monitored_url_guid' => null,
        'event_type' => null,
        'status_code' => null,
        'message' => null,
        'event_at' => null,
        'event_at_time_zone' => null,
    ];
}
