#!/usr/bin/env bash

touch .env.override
docker-compose up -d
docker exec -it --user root php-mission-control bash -c "chmod +x /app/scripts/ensureComposerInstall.sh && /app/scripts/ensureComposerInstall.sh"
docker exec -it --user root --workdir /app-volume php-mission-control bash -c "chmod +x /app/scripts/queueRunner.sh && /app/scripts/queueRunner.sh"
