#!/usr/bin/env bash

docker kill node-mission-control
./up
docker exec -it --user root node-mission-control bash -c "chmod +x /app/scripts/dev/ensureNpmInstall.sh && /app/scripts/dev/ensureNpmInstall.sh"
docker exec -it --user root --workdir /app node-mission-control bash -c "npm run fab"
