<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineJobItem;

use Atlas\Table\Table;

/**
 * @method PipelineJobItemRow|null fetchRow($primaryVal)
 * @method PipelineJobItemRow[] fetchRows(array $primaryVals)
 * @method PipelineJobItemTableSelect select(array $whereEquals = [])
 * @method PipelineJobItemRow newRow(array $cols = [])
 * @method PipelineJobItemRow newSelectedRow(array $cols)
 */
class PipelineJobItemTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'pipeline_job_items';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'pipeline_guid' => [
            'name' => 'pipeline_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'pipeline_job_guid' => [
            'name' => 'pipeline_job_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'pipeline_item_guid' => [
            'name' => 'pipeline_item_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'order' => [
            'name' => 'order',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'has_failed' => [
            'name' => 'has_failed',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'log_content' => [
            'name' => 'log_content',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'finished_at' => [
            'name' => 'finished_at',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'finished_at_time_zone' => [
            'name' => 'finished_at_time_zone',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'pipeline_guid',
        'pipeline_job_guid',
        'pipeline_item_guid',
        'order',
        'has_failed',
        'log_content',
        'finished_at',
        'finished_at_time_zone',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'pipeline_guid' => 'NULL',
        'pipeline_job_guid' => 'NULL',
        'pipeline_item_guid' => 'NULL',
        'order' => null,
        'has_failed' => 0,
        'log_content' => null,
        'finished_at' => 'NULL',
        'finished_at_time_zone' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
