<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Server;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $project_guid binary(16)
 * @property mixed $remote_service_adapter varchar(255)
 * @property mixed $remote_id varchar(255)
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $address varchar(255) NOT NULL
 * @property mixed $ssh_port varchar(255) NOT NULL
 * @property mixed $ssh_key_guid binary(16)
 * @property mixed $ssh_user_name varchar(255) NOT NULL
 */
class ServerRow extends Row
{
    protected $cols = [
        'guid' => null,
        'project_guid' => 'NULL',
        'remote_service_adapter' => 'NULL',
        'remote_id' => 'NULL',
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'address' => null,
        'ssh_port' => null,
        'ssh_key_guid' => 'NULL',
        'ssh_user_name' => null,
    ];
}
