<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Server;

use Atlas\Table\Table;

/**
 * @method ServerRow|null fetchRow($primaryVal)
 * @method ServerRow[] fetchRows(array $primaryVals)
 * @method ServerTableSelect select(array $whereEquals = [])
 * @method ServerRow newRow(array $cols = [])
 * @method ServerRow newSelectedRow(array $cols)
 */
class ServerTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'servers';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'project_guid' => [
            'name' => 'project_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'remote_service_adapter' => [
            'name' => 'remote_service_adapter',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'remote_id' => [
            'name' => 'remote_id',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'is_active' => [
            'name' => 'is_active',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 1,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'slug' => [
            'name' => 'slug',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'address' => [
            'name' => 'address',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'ssh_port' => [
            'name' => 'ssh_port',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'ssh_key_guid' => [
            'name' => 'ssh_key_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'ssh_user_name' => [
            'name' => 'ssh_user_name',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'project_guid',
        'remote_service_adapter',
        'remote_id',
        'is_active',
        'title',
        'slug',
        'address',
        'ssh_port',
        'ssh_key_guid',
        'ssh_user_name',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'project_guid' => 'NULL',
        'remote_service_adapter' => 'NULL',
        'remote_id' => 'NULL',
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'address' => null,
        'ssh_port' => null,
        'ssh_key_guid' => 'NULL',
        'ssh_user_name' => null,
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
