<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Reminder;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $project_guid binary(16)
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $message varchar(255) NOT NULL
 * @property mixed $added_at datetime NOT NULL
 * @property mixed $added_at_time_zone varchar(255) NOT NULL
 */
class ReminderRow extends Row
{
    protected $cols = [
        'guid' => null,
        'project_guid' => 'NULL',
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'message' => null,
        'added_at' => null,
        'added_at_time_zone' => null,
    ];
}
