<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Project;

/**
 * @property mixed $guid varchar(255) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $description varchar(255) NOT NULL
 * @property mixed $added_at datetime NOT NULL
 * @property mixed $added_at_time_zone varchar(255) NOT NULL
 */
trait ProjectFields
{
}
