<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Project;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $description varchar(255) NOT NULL
 * @property mixed $key_value_items text(65535)
 * @property mixed $added_at datetime NOT NULL
 * @property mixed $added_at_time_zone varchar(255) NOT NULL
 */
class ProjectRow extends Row
{
    protected $cols = [
        'guid' => null,
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'description' => null,
        'key_value_items' => 'NULL',
        'added_at' => null,
        'added_at_time_zone' => null,
    ];
}
