<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\TicketThreadItem;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $ticket_guid binary(16)
 * @property mixed $user_guid binary(16)
 * @property mixed $content text(65535)
 * @property mixed $added_at_utc datetime NOT NULL
 * @property mixed $has_been_modified tinyint(3,0) NOT NULL
 * @property mixed $modified_at_utc datetime
 */
class TicketThreadItemRow extends Row
{
    protected $cols = [
        'guid' => null,
        'ticket_guid' => 'NULL',
        'user_guid' => 'NULL',
        'content' => 'NULL',
        'added_at_utc' => null,
        'has_been_modified' => 0,
        'modified_at_utc' => 'NULL',
    ];
}
