<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\TicketThreadItem;

use Atlas\Table\Table;

/**
 * @method TicketThreadItemRow|null fetchRow($primaryVal)
 * @method TicketThreadItemRow[] fetchRows(array $primaryVals)
 * @method TicketThreadItemTableSelect select(array $whereEquals = [])
 * @method TicketThreadItemRow newRow(array $cols = [])
 * @method TicketThreadItemRow newSelectedRow(array $cols)
 */
class TicketThreadItemTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'ticket_thread_items';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'ticket_guid' => [
            'name' => 'ticket_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'user_guid' => [
            'name' => 'user_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'content' => [
            'name' => 'content',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'added_at_utc' => [
            'name' => 'added_at_utc',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'has_been_modified' => [
            'name' => 'has_been_modified',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'modified_at_utc' => [
            'name' => 'modified_at_utc',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'ticket_guid',
        'user_guid',
        'content',
        'added_at_utc',
        'has_been_modified',
        'modified_at_utc',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'ticket_guid' => 'NULL',
        'user_guid' => 'NULL',
        'content' => 'NULL',
        'added_at_utc' => null,
        'has_been_modified' => 0,
        'modified_at_utc' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
