<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\TicketThreadItem;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $ticket_guid binary(16)
 * @property mixed $user_guid binary(16)
 * @property mixed $content text(65535)
 * @property mixed $added_at_utc datetime NOT NULL
 * @property mixed $has_been_modified tinyint(3,0) NOT NULL
 * @property mixed $modified_at_utc datetime
 */
trait TicketThreadItemFields
{
}
