<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\PipelineItemServer;

use Atlas\Table\Table;

/**
 * @method PipelineItemServerRow|null fetchRow($primaryVal)
 * @method PipelineItemServerRow[] fetchRows(array $primaryVals)
 * @method PipelineItemServerTableSelect select(array $whereEquals = [])
 * @method PipelineItemServerRow newRow(array $cols = [])
 * @method PipelineItemServerRow newSelectedRow(array $cols)
 */
class PipelineItemServerTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'pipeline_item_servers';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'pipeline_item_guid' => [
            'name' => 'pipeline_item_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'server_guid' => [
            'name' => 'server_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'pipeline_item_guid',
        'server_guid',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'pipeline_item_guid' => null,
        'server_guid' => null,
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
