<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\NotificationEmail;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $email_address text(65535) NOT NULL
 */
class NotificationEmailRow extends Row
{
    protected $cols = [
        'guid' => null,
        'is_active' => 1,
        'email_address' => null,
    ];
}
