<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\NotificationEmail;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $email_address text(65535) NOT NULL
 */
trait NotificationEmailFields
{
}
