FROM buzzingpixel/php7.2:1.0.6
COPY . /app
COPY ./serverConfig/php/php-custom-config.ini /usr/local/etc/php/conf.d/php-custom-config.ini
COPY ./serverConfig/php/php-config-prod.ini /usr/local/etc/php/conf.d/php-env-config.ini
COPY ./serverConfig/php/fpm-www.conf /usr/local/etc/php-fpm.d/www.conf
