<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Ping;

use Atlas\Table\Row;

/**
 * @property mixed $guid varchar(255) NOT NULL
 * @property mixed $project_guid varchar(255) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $pending_error tinyint(3,0) NOT NULL
 * @property mixed $has_error tinyint(3,0) NOT NULL
 * @property mixed $expect_every bigint(20,0) unsigned NOT NULL
 * @property mixed $warn_after bigint(20,0) unsigned NOT NULL
 * @property mixed $last_ping_at datetime NOT NULL
 * @property mixed $last_ping_at_time_zone varchar(255) NOT NULL
 * @property mixed $added_at datetime NOT NULL
 * @property mixed $added_at_time_zone varchar(255) NOT NULL
 */
class PingRow extends Row
{
    protected $cols = [
        'guid' => null,
        'project_guid' => null,
        'is_active' => '1',
        'title' => null,
        'slug' => null,
        'pending_error' => '0',
        'has_error' => '0',
        'expect_every' => null,
        'warn_after' => null,
        'last_ping_at' => null,
        'last_ping_at_time_zone' => null,
        'added_at' => null,
        'added_at_time_zone' => null,
    ];
}
