<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Ticket;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $created_by_user_guid binary(16)
 * @property mixed $assigned_to_user_guid binary(16)
 * @property mixed $content text(65535)
 * @property mixed $status enum(11) NOT NULL
 * @property mixed $added_at_utc datetime NOT NULL
 * @property mixed $resolved_at_utc datetime
 */
trait TicketFields
{
}
