<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Ticket;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $created_by_user_guid binary(16)
 * @property mixed $assigned_to_user_guid binary(16)
 * @property mixed $title text(65535)
 * @property mixed $content text(65535)
 * @property mixed $status enum(11) NOT NULL
 * @property mixed $added_at_utc datetime NOT NULL
 * @property mixed $resolved_at_utc datetime
 */
class TicketRow extends Row
{
    protected $cols = [
        'guid' => null,
        'created_by_user_guid' => 'NULL',
        'assigned_to_user_guid' => 'NULL',
        'title' => 'NULL',
        'content' => 'NULL',
        'status' => '\'new\'',
        'added_at_utc' => null,
        'resolved_at_utc' => 'NULL',
    ];
}
