<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\TicketWatcher;

use Atlas\Table\Table;

/**
 * @method TicketWatcherRow|null fetchRow($primaryVal)
 * @method TicketWatcherRow[] fetchRows(array $primaryVals)
 * @method TicketWatcherTableSelect select(array $whereEquals = [])
 * @method TicketWatcherRow newRow(array $cols = [])
 * @method TicketWatcherRow newSelectedRow(array $cols)
 */
class TicketWatcherTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'ticket_watchers';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'ticket_guid' => [
            'name' => 'ticket_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'user_guid' => [
            'name' => 'user_guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => false,
            'default' => 'NULL',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'ticket_guid',
        'user_guid',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'ticket_guid' => 'NULL',
        'user_guid' => 'NULL',
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
