<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\TicketWatcher;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $ticket_guid binary(16)
 * @property mixed $user_guid binary(16)
 */
trait TicketWatcherFields
{
}
