<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\MonitoredUrl;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) NOT NULL
 * @property mixed $guid varchar(255) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $url varchar(255) NOT NULL
 * @property mixed $pending_error tinyint(3,0) NOT NULL
 * @property mixed $has_error tinyint(3,0) NOT NULL
 * @property mixed $checked_at datetime NOT NULL
 * @property mixed $checked_at_time_zone varchar(255) NOT NULL
 * @property mixed $added_at datetime NOT NULL
 * @property mixed $added_at_time_zone varchar(255) NOT NULL
 */
class MonitoredUrlRow extends Row
{
    protected $cols = [
        'id' => null,
        'guid' => null,
        'is_active' => '1',
        'title' => null,
        'slug' => null,
        'url' => null,
        'pending_error' => '0',
        'has_error' => '0',
        'checked_at' => null,
        'checked_at_time_zone' => null,
        'added_at' => null,
        'added_at_time_zone' => null,
    ];
}
