<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\Pipeline;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $project_guid binary(16)
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $description varchar(255) NOT NULL
 * @property mixed $secret_id varchar(255) NOT NULL
 */
class PipelineRow extends Row
{
    protected $cols = [
        'guid' => null,
        'project_guid' => 'NULL',
        'title' => null,
        'slug' => null,
        'description' => null,
        'secret_id' => null,
    ];
}
