<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\SshKey;

use Atlas\Table\Table;

/**
 * @method SshKeyRow|null fetchRow($primaryVal)
 * @method SshKeyRow[] fetchRows(array $primaryVals)
 * @method SshKeyTableSelect select(array $whereEquals = [])
 * @method SshKeyRow newRow(array $cols = [])
 * @method SshKeyRow newSelectedRow(array $cols)
 */
class SshKeyTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'ssh_keys';

    const COLUMNS = [
        'guid' => [
            'name' => 'guid',
            'type' => 'binary',
            'size' => 16,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'is_active' => [
            'name' => 'is_active',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 1,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'slug' => [
            'name' => 'slug',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'public' => [
            'name' => 'public',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'private' => [
            'name' => 'private',
            'type' => 'text',
            'size' => 65535,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'guid',
        'is_active',
        'title',
        'slug',
        'public',
        'private',
    ];

    const COLUMN_DEFAULTS = [
        'guid' => null,
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'public' => null,
        'private' => null,
    ];

    const PRIMARY_KEY = [
        'guid',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
