<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace src\app\data\SshKey;

use Atlas\Table\Row;

/**
 * @property mixed $guid binary(16) NOT NULL
 * @property mixed $is_active tinyint(3,0) NOT NULL
 * @property mixed $title varchar(255) NOT NULL
 * @property mixed $slug varchar(255) NOT NULL
 * @property mixed $public text(65535) NOT NULL
 * @property mixed $private text(65535) NOT NULL
 */
class SshKeyRow extends Row
{
    protected $cols = [
        'guid' => null,
        'is_active' => 1,
        'title' => null,
        'slug' => null,
        'public' => null,
        'private' => null,
    ];
}
